/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIVirtualFileSystem;

/**
 * A service used by FileSystemProvider to manage all virtual file systems
 */
[scriptable, uuid(5f1c80e1-ae01-408f-97e7-5ebce3bd611a)]
interface nsIVirtualFileSystemService : nsISupports
{
  // Get virtual file system instance with the file system identify.
  nsIVirtualFileSystem getVirtualFileSystemById(in DOMString fileSystemId);
};

%{C++
#define VIRTUALFILESYSTEMSERVICE_CID \
  {0xd3abe44a, 0x4098, 0x11e5, {0x8f, 0xd7, 0xdb, 0x52, 0x1d, 0x5d, 0x46, 0xb0}}
#define VIRTUAL_FILE_SYSTEM_SERVICE_CONTRACT_ID \
  "@mozilla.org/virtualfilesystem/virtualfilesystem-service;1"
%}