/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIArray;
interface nsIVirtualFileSystemCallback;
interface nsIVirtualFileSystemInfo;
interface nsIVirtualFileSystemMountRequestedOptions;
interface nsIVirtualFileSystemRequestManager;
interface nsIVirtualFileSystemUnmountRequestedOptions;

/**
 * A service used by FileSystemProvider to manage all cloud storages.
 */
[scriptable, uuid(04f7727c-b9e9-4e87-9525-be7aac4bf28f)]
interface nsIVirtualFileSystemService : nsISupports
{
  // Create cloud storage with the specified name.
  void mount(in nsIVirtualFileSystemMountRequestedOptions options,
             in nsIVirtualFileSystemRequestManager requestManager,
             in nsIVirtualFileSystemCallback callback);

  // Remove cloud storage with the specified file system identify.
  void unmount(in nsIVirtualFileSystemUnmountRequestedOptions options,
               in nsIVirtualFileSystemCallback callback);

  // Get cloud storage instance with the file system identify.
  nsIVirtualFileSystemInfo getVirtualFileSystemById(in DOMString fileSystemId);

  // Get the total number of virtual file systems
  nsIArray getAllVirtualFileSystem();

  // This is for testing.
  nsIVirtualFileSystemRequestManager getRequestManagerById(in DOMString fileSystemId);
};

%{C++
#define VIRTUALFILESYSTEMSERVICE_CID \
  {0xd3abe44a, 0x4098, 0x11e5, {0x8f, 0xd7, 0xdb, 0x52, 0x1d, 0x5d, 0x46, 0xb0}}
#define VIRTUAL_FILE_SYSTEM_SERVICE_CONTRACT_ID \
  "@mozilla.org/virtualfilesystem/virtualfilesystem-service;1"
%}